apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: requestflow

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - /etc/prometheus/requestflow-alerts.yml

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets:
              - "localhost:9090"

      - job_name: "requestflow-backend"
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "requestflow-backend:8000"

  requestflow-alerts.yml: |
    groups:
      - name: requestflow-availability
        rules:
          - alert: RequestFlowBackendDown
            expr: up{job="requestflow-backend"} == 0
            for: 1m

            labels:
              severity: critical
              service: requestflow-backend

            annotations:
              summary: "RequestFlow backend is unavailable"
              description: "Prometheus has been unable to scrape {{ $labels.instance }} for more than one minute."