apiVersion: v1
kind: Service
metadata:
  name: requestflow-backend
  namespace: requestflow
spec:
  type: ClusterIP
  selector:
    app: requestflow-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestflow-backend
  namespace: requestflow
spec:
  replicas: 1

  selector:
    matchLabels:
      app: requestflow-backend

  template:
    metadata:
      labels:
        app: requestflow-backend

    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16

          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: requestflow-config
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: requestflow-config
                  key: POSTGRES_DB

          command:
            - sh
            - -c
            - |
              until pg_isready \
                -h requestflow-postgres \
                -U "$POSTGRES_USER" \
                -d "$POSTGRES_DB";
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

      containers:
        - name: backend
          image: requestflow-backend:dev
          imagePullPolicy: Never

          command:
            - uvicorn

          args:
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"

          ports:
            - name: http
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: requestflow-config

            - secretRef:
                name: requestflow-secret

          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi