apiVersion: v1
kind: Secret
metadata:
  name: requestflow-secret
  namespace: requestflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "replace-with-a-local-kubernetes-password"
  JWT_SECRET_KEY: "replace-with-a-long-random-secret"
  DATABASE_URL: "postgresql+psycopg://requestflow_user:replace-with-a-local-kubernetes-password@requestflow-postgres:5432/requestflow_db"